name: Create SBOM

on:
  workflow_dispatch

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ env.REGISTRY_LOGIN }}/${{ env.REGISTRY_IMAGE }}:latest
          dependency-snapshot: true